title: "Sreeniyathi Kasireddy"
description: "Embedded Systems | Edge Computing | NLP | AI | ML"
theme: jekyll-theme-cayman

github:
  is_project_page: false
  owner_name: Sreeniyathi Kasireddy
  owner_url: https://github.com/Niyathi24
