title: "Sreeniyathi Kasireddy"
description: "Embedded Systems | Edge Computing | NLP | AI | ML"
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

github:
  is_project_page: false
  owner_name: Sreeniyathi Kasireddy
  owner_url: https://niyathi24.github.io/Niyathi24/
